version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
